@startuml
hide empty description
[*] -left-> Idle : /send(lead_Off)

Idle --> Helping : /send(lead_On)
Helping --> Idle : /send(lead_Off)
Helping -> LifeSaving : ledOn == true
LifeSaving --> Helping : /send(defibrillate)
LifeSaving --> Idle :  /send(lead_Off)

@enduml
